import { Rubik } from "next/font/google";
import "./globals.css";

// Configure Rubik font
const rubik = Rubik({
  variable: "--font-rubik", // CSS variable for Rubik
  subsets: ["latin"], // Subset for Latin characters
  weight: ["300", "400", "500", "700"], // Specify desired weights
  display: "swap", // Ensure font loads with fallback
});

export const metadata = {
  title: "SunnyRock",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" /> {/* Keep your favicon */}
      </head>
      <body className={rubik.variable}>{children}</body>
    </html>
  );
}
